### ISSUE TITLE
.mp4 file is not accessible | 403 - Access to this resource has been restricted

### ISSUE THREAD

**Issue by BoQsc** [DannyArends/DaNode#25]
Now who would not want to have an accessible video file.  
Today I really had a need to test out if DaNode would let me look at things such as images and videos on the web server.  
After some uploads, only the .png image file was accessible. The .mp4 file was blocked off. Not sure how to go about it.

![image](https://user-images.githubusercontent.com/21064622/146674718-fd64dcda-c712-4fa1-993c-fec02eac88d5.png)

http://78.140.136.25/1.mp4  This is a working link to a file that is .mp4 media. (Resource is Inaccessible)

http://78.140.136.25/2.png  Now the .png media file seems to show properly. (Resource is Accessible)

----
I suspect that mimetypes.d are lacking entry of .mp4
https://github.com/DannyArends/DaNode/blob/b12e8950e90ffaf9f86f5cf6c72d0bd2e5f08d8f/danode/mimetypes.d

**Comment by DannyArends** [comment]
Yes, mime-types are very incomplete... 

There are more defined in the development [branch](https://github.com/DannyArends/DaNode/tree/development) which I made suitable to run [Bludit CMS](https://github.com/bludit/bludit) next stop is [wordpress](https://github.com/WordPress/WordPress) but that still doesn't work

**Comment by BoQsc** [comment]
Just a note: adjusting the error so it won't mislead would be great.   
Something like: `MimeType .mp4 is missing in the danode/mimetypes.d`  
`Please fill an issue in the https://github.com/DannyArends/DaNode/issues`  

But that's not a priority, only a note.

**Comment by DannyArends** [comment]
Should be supported now
